from abc import ABC, abstractmethod


class ProcurementRepository(ABC):
    @abstractmethod
    def save_rfq(self, rfq): ...
    @abstractmethod
    def find_rfq_by_id(self, rid: str): ...
    @abstractmethod
    def find_rfqs(self, status: str = '') -> list: ...

    @abstractmethod
    def save_quotation(self, q): ...
    @abstractmethod
    def find_quotation_by_id(self, qid: str): ...
    @abstractmethod
    def find_quotations(self, rfq_id: str = '', supplier_id: str = '') -> list: ...

    @abstractmethod
    def save_award_decision(self, d): ...
    @abstractmethod
    def find_award_decision(self, aid: str): ...
    @abstractmethod
    def find_award_decisions(self, rfq_id: str = '') -> list: ...

    @abstractmethod
    def save_generated_po(self, po): ...

    @abstractmethod
    def save_counter_proposal(self, rfq_id: str, cp): ...
    @abstractmethod
    def find_counter_proposals(self, quotation_id: str = '') -> list: ...

    @abstractmethod
    def find_vendor_scores(self, supplier_id: str = '') -> list: ...

    @abstractmethod
    def save_purchase_order(self, po): ...
    @abstractmethod
    def find_purchase_orders(self, supplier_id: str = '', status: str = '') -> list: ...

    @abstractmethod
    def save_goods_receipt(self, gr): ...
    @abstractmethod
    def find_goods_receipts(self, po_id: str = '') -> list: ...
