from abc import ABC, abstractmethod
from modules.workflow.domain.entities.workflow import Workflow
from modules.workflow.domain.entities.state import WorkflowState
from modules.workflow.domain.entities.transition import WorkflowTransition
from modules.workflow.domain.entities.rule import WorkflowRule
from modules.workflow.domain.entities.instance import WorkflowInstance
from modules.workflow.domain.entities.history import WorkflowHistory
from modules.workflow.domain.entities.approval import WorkflowApproval
from modules.workflow.domain.entities.assignment import WorkflowAssignment


class WorkflowRepository(ABC):
    @abstractmethod
    def save_workflow(self, wf: Workflow) -> Workflow: ...
    @abstractmethod
    def find_workflow_by_id(self, wf_id: str) -> Workflow | None: ...
    @abstractmethod
    def find_workflow_by_code(self, code: str) -> Workflow | None: ...
    @abstractmethod
    def find_all_workflows(self, document_type: str = '') -> list[Workflow]: ...

    @abstractmethod
    def save_state(self, state: WorkflowState) -> WorkflowState: ...
    @abstractmethod
    def find_states_by_workflow(self, workflow_id: str) -> list[WorkflowState]: ...
    @abstractmethod
    def find_state_by_id(self, state_id: str) -> WorkflowState | None: ...

    @abstractmethod
    def save_transition(self, transition: WorkflowTransition) -> WorkflowTransition: ...
    @abstractmethod
    def find_transitions_by_workflow(self, workflow_id: str) -> list[WorkflowTransition]: ...
    @abstractmethod
    def find_transitions_from_state(self, workflow_id: str, state_id: str) -> list[WorkflowTransition]: ...

    @abstractmethod
    def save_rule(self, rule: WorkflowRule) -> WorkflowRule: ...
    @abstractmethod
    def find_rules_by_transition(self, transition_id: str) -> list[WorkflowRule]: ...
    @abstractmethod
    def find_rules_by_workflow(self, workflow_id: str) -> list[WorkflowRule]: ...

    @abstractmethod
    def save_instance(self, instance: WorkflowInstance) -> WorkflowInstance: ...
    @abstractmethod
    def find_instance_by_id(self, inst_id: str) -> WorkflowInstance | None: ...
    @abstractmethod
    def find_instances_by_document(self, document_type: str, document_id: str) -> list[WorkflowInstance]: ...
    @abstractmethod
    def find_instances_by_workflow(self, workflow_id: str, status: str = '') -> list[WorkflowInstance]: ...
    @abstractmethod
    def find_instances_by_state(self, state_id: str) -> list[WorkflowInstance]: ...

    @abstractmethod
    def save_history(self, history: WorkflowHistory) -> WorkflowHistory: ...
    @abstractmethod
    def find_history_by_instance(self, instance_id: str) -> list[WorkflowHistory]: ...

    @abstractmethod
    def save_approval(self, approval: WorkflowApproval) -> WorkflowApproval: ...
    @abstractmethod
    def find_approvals_by_instance(self, instance_id: str) -> list[WorkflowApproval]: ...
    @abstractmethod
    def find_pending_approvals(self, role: str = '') -> list[WorkflowApproval]: ...

    @abstractmethod
    def save_assignment(self, assignment: WorkflowAssignment) -> WorkflowAssignment: ...
    @abstractmethod
    def find_assignments_by_transition(self, transition_id: str) -> list[WorkflowAssignment]: ...
