from abc import ABC, abstractmethod
from modules.warehouse.domain.entities.warehouse import Warehouse
from modules.warehouse.domain.entities.stock_item import StockItem
from modules.warehouse.domain.entities.stock_movement import StockMovement
from modules.warehouse.domain.entities.inventory_count import InventoryCount


class WarehouseRepository(ABC):
    @abstractmethod
    def save_warehouse(self, warehouse: Warehouse) -> Warehouse: ...
    @abstractmethod
    def find_all_warehouses(self, query: str = '', active: bool | None = None) -> list[Warehouse]: ...
    @abstractmethod
    def find_warehouse_by_id(self, wh_id: str) -> Warehouse | None: ...

    @abstractmethod
    def save_stock_item(self, stock: StockItem) -> StockItem: ...
    @abstractmethod
    def find_stock_item(self, warehouse_id: str, item_id: str) -> StockItem | None: ...
    @abstractmethod
    def find_stock_by_warehouse(self, warehouse_id: str) -> list[StockItem]: ...
    @abstractmethod
    def find_stock_by_item(self, item_id: str) -> list[StockItem]: ...
    @abstractmethod
    def find_low_stock(self) -> list[StockItem]: ...

    @abstractmethod
    def save_movement(self, movement: StockMovement) -> StockMovement: ...
    @abstractmethod
    def find_movements_by_item(self, item_id: str) -> list[StockMovement]: ...
    @abstractmethod
    def find_movements_by_warehouse(self, warehouse_id: str) -> list[StockMovement]: ...

    @abstractmethod
    def save_inventory_count(self, count: InventoryCount) -> InventoryCount: ...
    @abstractmethod
    def find_counts_by_warehouse(self, warehouse_id: str) -> list[InventoryCount]: ...
