from abc import ABC, abstractmethod


class PurchaseRepository(ABC):
    # Purchase Requests
    @abstractmethod
    def save_purchase_request(self, pr): ...
    @abstractmethod
    def find_purchase_request_by_id(self, prid: str): ...
    @abstractmethod
    def find_purchase_requests(self, status: str = '', requestor: str = '') -> list: ...

    # Purchase Requisitions
    @abstractmethod
    def save_purchase_requisition(self, pr): ...
    @abstractmethod
    def find_purchase_requisition_by_id(self, prid: str): ...
    @abstractmethod
    def find_purchase_requisitions(self, status: str = '') -> list: ...

    # RFQs
    @abstractmethod
    def save_rfq(self, rfq): ...
    @abstractmethod
    def find_rfq_by_id(self, rid: str): ...
    @abstractmethod
    def find_rfqs(self, status: str = '') -> list: ...

    # Supplier Quotations
    @abstractmethod
    def save_quotation(self, q): ...
    @abstractmethod
    def find_quotation_by_id(self, qid: str): ...
    @abstractmethod
    def find_quotations(self, rfq_id: str = '', supplier_id: str = '') -> list: ...

    # Purchase Orders
    @abstractmethod
    def save_purchase_order(self, po): ...
    @abstractmethod
    def find_purchase_order_by_id(self, po_id: str): ...
    @abstractmethod
    def find_purchase_order_by_document(self, document_id: str): ...
    @abstractmethod
    def find_purchase_orders(self, supplier_id: str = '', status: str = '') -> list: ...

    # Goods Receipts
    @abstractmethod
    def save_goods_receipt(self, gr): ...
    @abstractmethod
    def find_goods_receipts(self, po_id: str = '') -> list: ...

    # Purchase Returns
    @abstractmethod
    def save_purchase_return(self, pr): ...
    @abstractmethod
    def find_purchase_returns(self, po_id: str = '') -> list: ...

    # Supplier Agreements
    @abstractmethod
    def save_supplier_agreement(self, a): ...
    @abstractmethod
    def find_supplier_agreements(self, supplier_id: str = '') -> list: ...
    @abstractmethod
    def find_supplier_agreement_by_id(self, aid: str): ...

    # Approval Matrix
    @abstractmethod
    def save_approval_rule(self, r): ...
    @abstractmethod
    def find_approval_rules(self, scope: str = '') -> list: ...

    # Vendor Score
    @abstractmethod
    def save_vendor_score(self, vs): ...
    @abstractmethod
    def find_vendor_scores(self, supplier_id: str = '') -> list: ...
