from abc import ABC, abstractmethod
from modules.inventory.domain.entities.stock_movement import StockMovement
from modules.inventory.domain.entities.location import Location
from modules.inventory.domain.entities.lot import Lot
from modules.inventory.domain.entities.serial_number import SerialNumber
from modules.inventory.domain.entities.reservation import Reservation
from modules.inventory.domain.entities.transfer_order import TransferOrder
from modules.inventory.domain.entities.inventory_count import InventoryCount


class InventoryRepository(ABC):
    # ── Stock Ledger ─────────────────────────────────────────
    @abstractmethod
    def save_movement(self, movement: StockMovement) -> StockMovement: ...
    @abstractmethod
    def find_movement_by_id(self, mov_id: str) -> StockMovement | None: ...
    @abstractmethod
    def find_movements(self, item_id: str = '', warehouse_id: str = '',
                       movement_type: str = '', reference_type: str = '',
                       limit: int = 100) -> list[StockMovement]: ...
    @abstractmethod
    def compute_balance(self, item_id: str, warehouse_id: str = '',
                        location_id: str = '', lot_id: str = '') -> float: ...
    @abstractmethod
    def compute_available(self, item_id: str, warehouse_id: str = '') -> float: ...

    # ── Locations ────────────────────────────────────────────
    @abstractmethod
    def save_location(self, location: Location) -> Location: ...
    @abstractmethod
    def find_locations_by_warehouse(self, warehouse_id: str) -> list[Location]: ...
    @abstractmethod
    def find_location_by_code(self, warehouse_id: str, code: str) -> Location | None: ...

    # ── Lots ─────────────────────────────────────────────────
    @abstractmethod
    def save_lot(self, lot: Lot) -> Lot: ...
    @abstractmethod
    def find_lot_by_id(self, lot_id: str) -> Lot | None: ...
    @abstractmethod
    def find_lots_by_item(self, item_id: str, warehouse_id: str = '') -> list[Lot]: ...
    @abstractmethod
    def find_expiring_lots(self, days: int) -> list[Lot]: ...
    @abstractmethod
    def find_expired_lots(self) -> list[Lot]: ...

    # ── Serials ──────────────────────────────────────────────
    @abstractmethod
    def save_serial(self, serial: SerialNumber) -> SerialNumber: ...
    @abstractmethod
    def find_serial(self, serial: str) -> SerialNumber | None: ...
    @abstractmethod
    def find_serials(self, item_id: str = '', warehouse_id: str = '',
                     status: str = '') -> list[SerialNumber]: ...

    # ── Reservations ─────────────────────────────────────────
    @abstractmethod
    def save_reservation(self, reservation: Reservation) -> Reservation: ...
    @abstractmethod
    def find_reservations(self, item_id: str = '', warehouse_id: str = '',
                          status: str = '', order_type: str = '',
                          order_id: str = '') -> list[Reservation]: ...
    @abstractmethod
    def find_expired_reservations(self) -> list[Reservation]: ...

    # ── Transfers ────────────────────────────────────────────
    @abstractmethod
    def save_transfer(self, transfer: TransferOrder) -> TransferOrder: ...
    @abstractmethod
    def find_transfer_by_id(self, transfer_id: str) -> TransferOrder | None: ...
    @abstractmethod
    def find_transfers(self, warehouse_id: str = '', status: str = '') -> list[TransferOrder]: ...

    # ── Inventory Counts ─────────────────────────────────────
    @abstractmethod
    def save_count(self, count: InventoryCount) -> InventoryCount: ...
    @abstractmethod
    def find_counts_by_warehouse(self, warehouse_id: str) -> list[InventoryCount]: ...
