from abc import ABC, abstractmethod
from modules.document.domain.entities.business_document import BusinessDocument
from modules.document.domain.entities.document_definition import DocumentDefinition
from modules.document.domain.entities.document_numbering import DocumentNumbering


class DocumentRepository(ABC):
    @abstractmethod
    def save_document(self, doc: BusinessDocument) -> BusinessDocument: ...
    @abstractmethod
    def delete_document(self, doc_id: str) -> None: ...
    @abstractmethod
    def find_document_by_id(self, doc_id: str) -> BusinessDocument | None: ...
    @abstractmethod
    def find_documents(self, document_type: str = '', status: str = '',
                       party_id: str = '', query: str = '',
                       limit: int = 100) -> list[BusinessDocument]: ...
    @abstractmethod
    def find_documents_by_reference(self, reference_type: str, reference_id: str) -> list[BusinessDocument]: ...

    @abstractmethod
    def save_definition(self, defn: DocumentDefinition) -> DocumentDefinition: ...
    @abstractmethod
    def find_definition_by_id(self, def_id: str) -> DocumentDefinition | None: ...
    @abstractmethod
    def find_definition_by_code(self, code: str) -> DocumentDefinition | None: ...
    @abstractmethod
    def find_all_definitions(self, active: bool = True) -> list[DocumentDefinition]: ...

    @abstractmethod
    def save_numbering(self, numbering: DocumentNumbering) -> DocumentNumbering: ...
    @abstractmethod
    def find_numbering(self, document_type: str, series: str = '') -> DocumentNumbering | None: ...
    @abstractmethod
    def find_all_numbering(self) -> list[DocumentNumbering]: ...
