from abc import ABC, abstractmethod
from modules.sales.core.domain.entities.opportunity import Opportunity, Pipeline
from modules.sales.core.domain.entities.price_list import PriceList
from modules.sales.core.domain.entities.discount_rule import DiscountRule
from modules.sales.core.domain.entities.commission import CommissionRule, CommissionStatement
from modules.sales.core.domain.entities.contract import Contract
from modules.sales.core.domain.entities.delivery import Delivery
from modules.sales.core.domain.entities.return_request import ReturnRequest
from modules.sales.core.domain.entities.sales_order import SalesOrder


class SalesRepository(ABC):
    # Sales Orders
    @abstractmethod
    def save_sales_order(self, so: SalesOrder) -> SalesOrder: ...
    @abstractmethod
    def find_sales_order_by_id(self, so_id: str) -> SalesOrder | None: ...
    @abstractmethod
    def find_sales_order_by_document(self, document_id: str) -> SalesOrder | None: ...
    @abstractmethod
    def find_sales_orders(self, customer_id: str = '', status: str = '',
                          document_type: str = '', limit: int = 100) -> list: ...

    # Opportunities
    @abstractmethod
    def save_opportunity(self, opp: Opportunity) -> Opportunity: ...
    @abstractmethod
    def find_opportunity_by_id(self, opp_id: str) -> Opportunity | None: ...
    @abstractmethod
    def find_opportunities(self, customer_id: str = '', status: str = '',
                           sales_rep: str = '', limit: int = 100) -> list: ...

    # Pipelines
    @abstractmethod
    def save_pipeline(self, p: Pipeline) -> Pipeline: ...
    @abstractmethod
    def find_pipeline_by_id(self, pid: str) -> Pipeline | None: ...
    @abstractmethod
    def find_all_pipelines(self) -> list[Pipeline]: ...

    # Price Lists
    @abstractmethod
    def save_price_list(self, pl: PriceList) -> PriceList: ...
    @abstractmethod
    def find_price_list_by_id(self, pl_id: str) -> PriceList | None: ...
    @abstractmethod
    def find_price_list_by_code(self, code: str) -> PriceList | None: ...
    @abstractmethod
    def find_all_price_lists(self) -> list[PriceList]: ...

    # Discount Rules
    @abstractmethod
    def save_discount_rule(self, r: DiscountRule) -> DiscountRule: ...
    @abstractmethod
    def find_discount_rule_by_id(self, rid: str) -> DiscountRule | None: ...
    @abstractmethod
    def find_active_discount_rules(self) -> list[DiscountRule]: ...

    # Commissions
    @abstractmethod
    def save_commission_rule(self, r: CommissionRule) -> CommissionRule: ...
    @abstractmethod
    def find_commission_rules(self, sales_rep_id: str = '') -> list: ...
    @abstractmethod
    def save_statement(self, s: CommissionStatement) -> CommissionStatement: ...

    # Contracts
    @abstractmethod
    def save_contract(self, c: Contract) -> Contract: ...
    @abstractmethod
    def find_contract_by_id(self, cid: str) -> Contract | None: ...
    @abstractmethod
    def find_contracts(self, customer_id: str = '', status: str = '') -> list: ...

    # Deliveries
    @abstractmethod
    def save_delivery(self, d: Delivery) -> Delivery: ...
    @abstractmethod
    def find_delivery_by_id(self, did: str) -> Delivery | None: ...
    @abstractmethod
    def find_deliveries(self, document_id: str = '', status: str = '') -> list: ...

    # Returns
    @abstractmethod
    def save_return(self, r: ReturnRequest) -> ReturnRequest: ...
    @abstractmethod
    def find_returns(self, document_id: str = '', status: str = '') -> list: ...

    # ── Sales Experience ────────────────────────────────────────
    # Order Templates
    @abstractmethod
    def save_template(self, t): ...
    @abstractmethod
    def find_template_by_id(self, tid: str): ...  # noqa
    @abstractmethod
    def find_templates(self, customer_id: str = '') -> list: ...

    # Favorites
    @abstractmethod
    def save_favorite(self, f): ...
    @abstractmethod
    def find_favorites(self, customer_id: str) -> list: ...
    @abstractmethod
    def remove_favorite(self, favorite_id: str): ...

    # Price History
    @abstractmethod
    def save_price_history(self, entry): ...
    @abstractmethod
    def find_price_history(self, item_id: str, limit: int = 20) -> list: ...

    # Timeline
    @abstractmethod
    def save_timeline_entry(self, entry): ...
    @abstractmethod
    def find_timeline(self, document_id: str) -> list: ...

    # Sales Notes
    @abstractmethod
    def save_note(self, note): ...
    @abstractmethod
    def find_notes(self, document_id: str, note_type: str = '') -> list: ...

    # Tags
    @abstractmethod
    def save_tag(self, tag): ...
    @abstractmethod
    def find_tag_by_id(self, tag_id: str): ...  # noqa
    @abstractmethod
    def find_tags(self) -> list: ...

    # Team
    @abstractmethod
    def save_team_member(self, member): ...
    @abstractmethod
    def find_team_members(self, role: str = '') -> list: ...
    @abstractmethod
    def find_team_member_by_id(self, rep_id: str): ...  # noqa

    # Approval Matrix
    @abstractmethod
    def save_approval_rule(self, rule): ...
    @abstractmethod
    def find_approval_rules(self) -> list: ...
    @abstractmethod
    def find_approver_for_value(self, order_value: float) -> str: ...

    # ── Extensions ─────────────────────────────────────────
    # Credit
    @abstractmethod
    def save_credit(self, c): ...
    @abstractmethod
    def find_credit_by_customer(self, customer_id: str): ...

    # Bundles
    @abstractmethod
    def save_bundle(self, b): ...
    @abstractmethod
    def find_bundles(self) -> list: ...
    @abstractmethod
    def find_bundle_by_id(self, bid: str): ...

    # Campaigns
    @abstractmethod
    def save_campaign(self, c): ...
    @abstractmethod
    def find_campaigns(self) -> list: ...

    # Policies
    @abstractmethod
    def save_policy(self, p): ...
    @abstractmethod
    def find_policies(self) -> list: ...

    # Rules
    @abstractmethod
    def save_rule(self, r): ...
    @abstractmethod
    def find_rules(self) -> list: ...

    # Recommendations
    @abstractmethod
    def find_similar_items(self, item_id: str, limit: int = 3) -> list: ...
    @abstractmethod
    def find_cross_sell_items(self, item_id: str, limit: int = 3) -> list: ...
    @abstractmethod
    def find_up_sell_items(self, item_id: str, limit: int = 3) -> list: ...

    # Agreements
    @abstractmethod
    def save_agreement(self, a): ...
    @abstractmethod
    def find_agreements(self, customer_id: str = '') -> list: ...

    # Calendar
    @abstractmethod
    def save_calendar_event(self, e): ...
    @abstractmethod
    def find_calendar_events(self, sales_rep: str = '') -> list: ...

    # Customer Preferences
    @abstractmethod
    def save_customer_preferences(self, p: dict) -> dict: ...
    @abstractmethod
    def find_customer_preferences(self, customer_id: str) -> dict | None: ...

    # Audit
    @abstractmethod
    def save_audit_entry(self, e): ...
    @abstractmethod
    def find_audit_entries(self, entity_type: str = '', entity_id: str = '',
                           document_id: str = '') -> list: ...

    # Events
    @abstractmethod
    def save_event(self, e): ...
    @abstractmethod
    def find_events(self, document_id: str = '', customer_id: str = '') -> list: ...
